title: HVboom - HVLandscape
description: HVboom delivers High Value Business Oriented Object Models
email: Mario@HVboom.ch
github_username: HVboom

markdown: kramdown
highlighter: rouge
# kramdown:
#   syntax_highlighter_opts:
#     block:
#       line_numbers: true

strict_front_matter: true
baseurl: "/HVLandscape"
url: "https://jekyll.hvboom.org"
port: 8003
images: "/HVLandscape/assets/images/"

target-blank:
  add_css_classes: target-blank target-blank__icon

collections:
  applications:
    output: true
    permalink: "/apps/:path.html"
  links:
    output: true
    permalink: "/links/:path.html"
  topics:
    output: true
    permalink: "/topics/:path.html"
  utilities:
    output: true
    permalink: "/utils/:path.html"

theme: jekyll-text-theme

author:
  name: Mario Lotz
  type: # "person" (default), "organization"
  url:
  avatar: /assets/images/Mario.jpg
  bio:
  email: Mario@HVboom.ch
  linkedin: mario-lotz # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name
  github: HVboom # "user_name" the last part of your profile url, e.g. https://github.com/user_name

defaults:
  - scope:
      path: ""
    values:
      author: Mario
      layout: "article"
      full_width: false
      show_title: false
      show_tags: true
      aside:
        toc: true
  - scope:
      path: "_applications"
    values:
      nav_key: "applications"
      sidebar:
        nav: "applications"
  - scope:
      path: "_utilities"
    values:
      nav_key: "applications"
      sidebar:
        nav: "applications"
  - scope:
      path: "_topics"
    values:
      nav_key: "topics"
      sidebar:
        nav: "topics"
